### ISSUE TITLE
Problema con audífonos y notificaciones al escuchar música

### ISSUE THREAD

**Issue by alfredoweb** [ingbrzy/MA-XML-10-SPANISH-Global#10]
Hola, desde hace ya, varias versiones atrás, que este inconveniente no se ha solucionado, actualmente tengo el Redmi Note 4X 8.8.9, y todos los días, escucho música, en Spotify y en el reproductor de música que viene incorporado en la ROM, escucho la música con audífonos, y siempre que voy escuchando música, y me sale la alerta de batería baja, emite también el sonido de batería baja, y al emitir el sonido de batería baja, se detiene la música, suena por los audífonos y el alta voz, el sonido de batería baja y luego la música sigue sonando por el audífono, y suena adicionalmente por el altavoz, me ha traído muchas veces un mal rato, cómo voy con los audífonos, aveces no me doy cuenta cuando va sonando por el altavoz, y no solo me pasa con la notificación de batería baja.

**Comment by ghost** [comment]
Hola! Aquí solo tratamos temas de traducción no te podemos ayudar. Te recomiendo que vayas al último post publicado de Xiaomi.eu y expongas tu problema. Suerte!
