### ISSUE TITLE
Panel de personalizacion/ ajustes 

### ISSUE THREAD

**Issue by coryweed** [ingbrzy/MA-XML-10-SPANISH-Global#11]
![screenshot_2018-08-28-01-02-47-617_com miui personalassistant](https://user-images.githubusercontent.com/41973478/44691401-d14e0880-aa5e-11e8-8970-201d2af3dcbd.png)
![screenshot_2018-08-28-01-02-47-617_com miui personalassistant](https://user-images.githubusercontent.com/41973478/44691412-dad77080-aa5e-11e8-9948-70bcdb29895f.png)
![screenshot_2018-08-28-01-02-55-961_com miui personalassistant](https://user-images.githubusercontent.com/41973478/44691415-db700700-aa5e-11e8-8124-9702ed3498d5.png)

Cuando te metes a la izquierda del todo en el panel de personalizacion,los ajustes están en chino

**Comment by ghost** [comment]
Veré lo que puedo hacer..., no sé chino 😂

**Comment by ghost** [comment]
Arreglado gracias a @ScratchBuild :-)
