### ISSUE TITLE
Ajustes/pantalla de inicio y recientes

### ISSUE THREAD

**Issue by coryweed** [ingbrzy/MA-XML-10-SPANISH-Global#16]

**Comment by coryweed** [comment]
![img_20180901_011304](https://user-images.githubusercontent.com/41973478/44939492-ff488b00-ad85-11e8-9d89-82267162773b.jpg)

Hay un error de traducción en ajustes,pantalla de inicio y recientes

**Comment by ghost** [comment]
Gracias por avisar lo arreglo ahora :-) !
