### ISSUE TITLE
Error redireccion/link

### ISSUE THREAD

**Issue by mikeliturria** [ingbrzy/MA-XML-10-SPANISH-Global#17]
Error cuando redirecciona desde YouTube o chrome sale un mensaje de error sistema Android falló

**Comment by ghost** [comment]
Hola! Aquí solo tratamos problemas de la traducción :-( . Prueba ponerlo en inglés a ver si es problema de nuestra traducción, si no vete al foro de xiaomi.eu y comenta tu problema.

Un saludo!
