### ISSUE TITLE
Ajustes / Pantalla de bloqueo y contraseña / Ajustes avanzados

### ISSUE THREAD

**Issue by ghost** [ingbrzy/MA-XML-10-SPANISH-Global#22]
Vertical clock

http://imgur.com/gallery/tlqdYK9

**Comment by danielchc** [comment]
Ya lo habia arreglado 😛 
https://github.com/ingbrzy/MA-XML-10-SPANISH-Global/commit/da5eecb207a2b1470601642ef295976710155457#diff-71045f6baf582bca7e267f0f5bc85474R2210

Gracias por avisar de todas formas 😄
