### ISSUE TITLE
Pantalla de bloqueo / deslizar hacia la izquierda

### ISSUE THREAD

**Issue by ghost** [ingbrzy/MA-XML-10-SPANISH-Global#23]
Calculator
Notes

http://imgur.com/gallery/ydnIwhP

**Comment by danielchc** [comment]
Voy a ser muy sincero, lo había visto pero no encuentro las strings en la rom original


@ScratchBuild Can you help me to find "Calculator" and "Notes" in LockScreen. I didn't found in XML-Compare

![](https://i.imgur.com/CYlluUw.png)

**Comment by danielchc** [comment]
Forget it, sorry
