### ISSUE TITLE
Ajustes / Mi dispositivo

### ISSUE THREAD

**Issue by ghost** [ingbrzy/MA-XML-10-SPANISH-Global#24]
Aparece toda la información superior en inglés.

http://imgur.com/gallery/b041mr1

**Comment by danielchc** [comment]
No sé porque no aparece traducido, porque está traducido https://github.com/ingbrzy/MA-XML-10-SPANISH-Global/blob/master/Spanish/main/Settings.apk/res/values-es/arrays.xml#L1336

Espero encontrar una solución

**Comment by danielchc** [comment]
Creo que esto no se puede traducir, en los otros idiomas también está sin traducir
