### ISSUE TITLE
Ajustes / Ajustes adicionales / Opciones de desarrollador

### ISSUE THREAD

**Issue by ghost** [ingbrzy/MA-XML-10-SPANISH-Global#25]
Extended power menu

http://imgur.com/gallery/7q2Fh6p

**Comment by danielchc** [comment]
También arreglado ayer https://github.com/ingbrzy/MA-XML-10-SPANISH-Global/commit/86c9b9613f22096e5fe8dc4eb0a1dcac6cdb3fe5#diff-71045f6baf582bca7e267f0f5bc85474R1797
