### ISSUE TITLE
DocumentsUI.apk

### ISSUE THREAD

**Issue by danielchc** [ingbrzy/MA-XML-10-SPANISH-Global#26]
Why DocumentsUI.apk(com.android.documentsui) is unstranslated? 🤦‍♂️  And why doesn't exist in the Xiaomi.eu-MIUIv10-XML-Compare

@ingbrzy I beg you to answer the question

**Comment by ingbrzy** [comment]
recompile breaks apk.. so for now, we are not adding translations there..
