### ISSUE TITLE
GPS problem xiaomi.eu_multi_MI4s_V10.1.1.0.NAJCNFI_v10-7.0

### ISSUE THREAD

**Issue by Kentaion** [ingbrzy/MA-XML-10-SPANISH-Global#31]
I updated my Xiaomi Mi 4s a few day ago to this version (xiaomi.eu_multi_MI4s_V10.1.1.0.NAJCNFI_v10-7.0). When I was trying to use the GPS I noticed it did not work properly. In my last version it worked perfectly. My phone takes around 20 - 40 minutes to find the signals from the satellites, which I think it is not normal. I have tried to change the A-GPS configuration, the GPS configuration, the battery and perfomance configuration, re-installing the version,... (I have tried almost all the recomendations I have found on Internet). Additionally, I rooted the phone in order to find the file gps.conf in system/etc. I could not find it though. I think the problem could be related with the missing file gps.conf. I hope you can find this information usefull in order to find the problem with the GPS in this version.

Kind regards,

Juan Manuel

**Comment by danielchc** [comment]
Hi, this repository is only for problems with Spanish Translation. Please report the problem in xiaomi.eu
