### ISSUE TITLE
8.12.27 pantalla de bloqueo

### ISSUE THREAD

**Issue by ghost** [ingbrzy/MA-XML-10-SPANISH-Global#32]
En la pantalla de bloqueo al deslizar hacia la izquierda esta en ingles;

https://i.imgur.com/imBTb0F.jpg

**Comment by danielchc** [comment]
Gracias por avisar, mañana le echo un vistazo ;-)

**Comment by danielchc** [comment]
Listo, ya está solucionado!!
Gracias 😄
