### ISSUE TITLE
Ajustes - Sonido y vibración

### ISSUE THREAD

**Issue by ghost** [ingbrzy/MA-XML-10-SPANISH-Global#34]
Adjunto imagen

https://i.imgur.com/ErsXkUn.jpg

Ajustes - Sonido y Vibración, aparece el siguiente texto:

"Default volume control stream"

**Comment by danielchc** [comment]
Hola! Ya lo he solucionado el la commit de ayer e9fc3d53c00db675965c71b3b6c7f801ad3d09f2

Gracias! Cualquier cosa ya sabes 😄
