### ISSUE TITLE
Español(América) Responsable

### ISSUE THREAD

**Issue by melvingb** [ingbrzy/MA-XML-10-SPANISH-Global#35]
Hola, quisiera hacerme cargo de la traducción latinoamérica, solo necesito info del status en donde se quedo parado este proyecto.

**Comment by danielchc** [comment]
Hola, si te soy sincero ya no llevo cuenta de cuando la última traducción al español de latinoamerica... Está totalmente abandonado... Sería ponerse casi desde 0 de las cosas que se metieron en MIUI 10. Si te interesa, si sabes como va la cosa. Empieza traduciendo los archivos y envia Pull Request al repositorio. Si todo va bien hablaré para que te dean permisos

**Comment by danielchc** [comment]
Lo cierro porque no obtuve respuesta
