### ISSUE TITLE
SMS app mal traducida

### ISSUE THREAD

**Issue by numind06** [ingbrzy/MA-XML-10-SPANISH-Global#36]
Por fin alguien se dio cuenta de que el airplane mode estaba sin traducir, parece que lo han solucionado en el ultimo update del MIUI.

Sin embargo la app para los SMS tiene la parte de borrar los mensajes sin traducir, solo esta bien el "cancelar"..

No se si pertenece a la interfaz MIUI o es mas bien de la propia app.

Ahi lo dejo...

**Comment by danielchc** [comment]
Hola! me podrías mandar una captura porfa. No encuentro lo que dices :/. 
Yo me guio por lo que veo en mi móvil y está todo traducido, no sé que puede pasar en otros modelos

**Comment by danielchc** [comment]
Sin respuesta
