### ISSUE TITLE
Carrusel de Fondos

### ISSUE THREAD

**Issue by Davidjarod11** [ingbrzy/MA-XML-10-SPANISH-Global#38]
Hola que tal observe que falta traducción en Mi cloud, bloqueo de aplicaciones, desbloqueo facial de aplicaciones , carrusel de fotos , Huella digital , espero y sirvan de ayuda las capturas, mi dispositivo (whyred -9.2.14)

Mi cloud

![whatsapp image 2019-02-17 at 14 27 45 1](https://user-images.githubusercontent.com/47721967/52918407-aa151d00-32c4-11e9-865e-047c241058e2.jpeg)
![whatsapp image 2019-02-17 at 14 27 45 2](https://user-images.githubusercontent.com/47721967/52918408-aaadb380-32c4-11e9-9217-1aee681abdb2.jpeg)
![whatsapp image 2019-02-17 at 14 27 45 5](https://user-images.githubusercontent.com/47721967/52918620-1d1f9300-32c7-11e9-83c0-3bcde2a08882.jpeg)

Bloqueo de aplicaciones
![whatsapp image 2019-02-17 at 14 32 29 2](https://user-images.githubusercontent.com/47721967/52918421-c2853780-32c4-11e9-9220-e0d5d126d986.jpeg)

![whatsapp image 2019-02-17 at 14 32 29 1](https://user-images.githubusercontent.com/47721967/52918420-c2853780-32c4-11e9-8f38-1cfc4546a57d.jpeg)

Desbloqueo facial de aplicaciones.( discúlpame la calidad.. lo que pasa es que no deja sacar capturas en esta pantalla ni grabar , me imagino por cuestiones de seguridad )

![sin tituloddd](https://user-images.githubusercontent.com/47721967/52918449-1ee85700-32c5-11e9-8ef7-8abb91308bd6.png)

Carrusel de fotos 

![whatsapp image 2019-02-17 at 14 32 29](https://user-images.githubusercontent.com/47721967/52918479-725aa500-32c5-11e9-8d49-4270f7e05497.jpeg)

Huella digital

![whatsapp image 2019-02-17 at 14 27 45](https://user-images.githubusercontent.com/47721967/52918485-84d4de80-32c5-11e9-85aa-7f5bfc655fc0.jpeg)
 
Bueno eso es lo que he visto hasta el momento , muchas gracias por su trabajo :)

**Comment by danielchc** [comment]
Hola, le echo un vistazo luego gracias!!

**Comment by Davidjarod11** [comment]
Gracias a ti :)

**Comment by danielchc** [comment]
Hola! He arreglado parte de las cosas que comentas. Tengo que revisar el carrusel y la huella dactilar porque no tengo claro porque se muestran los textos en inglés. Puedes revisar los cambios que hice el la última commit. Cualquier cosa ya sabes

**Comment by Davidjarod11** [comment]
Gracias , en cuanto a lo de la huella , el "try again" aparece cuando pones la huella varias veces muy rápido, espero y te ayude.

**Comment by Davidjarod11** [comment]
Hola aqui tengo otros 
![aee0df31-f39c-481e-be90-283c0f98d06f](https://user-images.githubusercontent.com/47721967/53292557-f57e6e00-3791-11e9-9550-5cdd42b25477.jpg)
![817d5501-3fe8-416a-aaf3-43cdc7d8042f](https://user-images.githubusercontent.com/47721967/53292564-08913e00-3792-11e9-81fe-ce54d8442ebb.jpg)
![10256933-6e5f-408d-abef-d2b7f76a9bf2](https://user-images.githubusercontent.com/47721967/53292565-08913e00-3792-11e9-95eb-29ce70f9cc43.jpg)

**Comment by danielchc** [comment]
Perfecto! Lo voy a intentar ir solucionando los próximos días. Soy yo solo con la traducción y estos días estoy ocupado. Pero tranquilo que no me olvido, prometo que lo antes que pueda estará solucionado 😄

**Comment by danielchc** [comment]
Una pregunta tienes por casualidad el telefono en Español América? Es que hay cosas que a mi si me aparecen traducidas :/ . La traducción de  Español América está obsoleta 😓

**Comment by Davidjarod11** [comment]
Hola que tal , en efecto estaba usando la versión de español américa, ya la cambie a español españa y reinicie el celular, revise una por una las imágenes y la única diferencia que veo es en la de configuración no molestar que en español españa si la muestra bien , por lo demás todo sigue igual ya lo verifique, ah y muchas gracias por la traducción en la ultima versión de micloud y lo de la app de seguridad, aunque aun falta, se agradece mucho, una ultima cosa , me explicas que el idioma en español américa esta obsoleto , yo lo tenia así,  sin embargo si notaba que cuando salia nueva versión se traducían nuevas cosas , incluso lo ultimo de micloud y seguridad se traducio, como es eso?

**Comment by Davidjarod11** [comment]
Actualmente estoy en la 9.2.21, con el español de España, ahí te paso imágenes actualizadas y encerrando las cosas que faltan para ayudarte.

1.  SOS

![whatsapp image 2019-02-25 at 01 44 01](https://user-images.githubusercontent.com/47721967/53319543-cdc9fb80-38a0-11e9-84b7-4aae0d205a8a.jpeg)

2. Mi cloud

![whatsapp image 2019-02-25 at 01 44 02](https://user-images.githubusercontent.com/47721967/53319567-dfab9e80-38a0-11e9-91cc-c8d04c738301.jpeg)

3. Detener escaneo batería 
![whatsapp image 2019-02-25 at 01 44 01 6](https://user-images.githubusercontent.com/47721967/53319669-2ac5b180-38a1-11e9-92be-b8789b259a2e.jpeg)

4. Bloqueo de aplicación y contraseña

![whatsapp image 2019-02-25 at 01 44 01 7](https://user-images.githubusercontent.com/47721967/53320079-7cbb0700-38a2-11e9-849a-57b9e2b89387.jpeg)

 
5.Ahorrador de batería.

![whatsapp image 2019-02-25 at 01 44 01 4](https://user-images.githubusercontent.com/47721967/53319826-b2132500-38a1-11e9-8261-65fad2e46e56.jpeg)
![whatsapp image 2019-02-25 at 01 44 01 5](https://user-images.githubusercontent.com/47721967/53320155-c3a8fc80-38a2-11e9-9213-8926979aed1d.jpeg)

 
6.Opciones de desarrollador

![whatsapp image 2019-02-25 at 01 44 01 8](https://user-images.githubusercontent.com/47721967/53319867-d8d15b80-38a1-11e9-946c-ab343fea197f.jpeg)
![whatsapp image 2019-02-25 at 01 44 01 1](https://user-images.githubusercontent.com/47721967/53319875-e1299680-38a1-11e9-96cf-65808abc63c2.jpeg)
![whatsapp image 2019-02-25 at 01 44 01 2](https://user-images.githubusercontent.com/47721967/53319880-e4bd1d80-38a1-11e9-931f-ed9450b2edf7.jpeg)

7. Intentar de nuevo huella digital
![whatsapp image 2019-02-25 at 01 44 01 3](https://user-images.githubusercontent.com/47721967/53319964-24840500-38a2-11e9-9e07-0d5ff8f3ed11.jpeg)


8. Desbloqueo facial de aplicaciones
![sin tituloddd](https://user-images.githubusercontent.com/47721967/53319998-39609880-38a2-11e9-820d-5e60dad5af85.png)

9. Carrusel de fotos 
![whatsapp image 2019-02-17 at 14 32 29](https://user-images.githubusercontent.com/47721967/53320025-48dfe180-38a2-11e9-9e9d-575613bb80ea.jpeg)
![whatsapp image 2019-02-17 at 14 27 45 3](https://user-images.githubusercontent.com/47721967/53320026-49787800-38a2-11e9-9b67-0373e0169667.jpeg)

**Comment by danielchc** [comment]
Las capturas 1, 2, 3, 4,5,6(creo que si),7,8 y el carrusel de fotos no lo pude terminar de traducir son 200 líneas y traducí parte. Jejeje, para la semana si tienes un momento me mandas las capturas de las cosas que veas que aún no traducí.

Respecto a lo de Español América, te explico mi teoría Android tiene un sistema de prioridades a la hora de la traducción, Si no encuentra la tradución en Español América(values-es-rUS), busca los archivos de idioma del Español Internacional (values-es), en último caso busca la traducción en inglés. Eso explicaría porque lo de "Silenciar sonidos %1$s excepto alarmas" está sin traducir, dado que existe una traducción en los archivos de Español ámerica y no va a buscar la del español. No sé si me expliqué :/

Me vas contando a ver ;)

**Comment by Davidjarod11** [comment]
Muchas gracias por la explicación, lo entendí perfectamente, ya vi las traducciones y vi que te tomaste la molestia de corregir el "Silenciar sonidos %1$s excepto alarmas" del español américa o eso es lo que me pareció ver :D , bueno en cuanto salga la nueva versión el día viernes te actualizo con lo que falta :)

**Comment by Davidjarod11** [comment]
Hola , aqui estan las imagenes actualizadas de las traducciones que faltan en la nueva version 9.3.1

1.Acelerador de juegos
![0faf4d32-d811-4541-9da1-cad00253577c](https://user-images.githubusercontent.com/47721967/53671811-07f31e80-3c4e-11e9-8f78-24bc27a1451d.jpg)

2. Ahorro de batería (*Aplicaciones suspendidas)
![whatsapp image 2019-03-01 at 18 09 40](https://user-images.githubusercontent.com/47721967/53671851-29eca100-3c4e-11e9-97d3-1bd905ee900a.jpeg)

3. Tutorial sobre aplicaciones ocultas ( 2 páginas en ingles)
![0479f5aa-16f5-418d-99f1-db46dfc2c731](https://user-images.githubusercontent.com/47721967/53671887-556f8b80-3c4e-11e9-9900-3ffb4d38f06f.jpg)
![66c8e740-7ad4-49da-b109-1ed6952298fc](https://user-images.githubusercontent.com/47721967/53671899-5f918a00-3c4e-11e9-8a4e-c207717db896.jpg)

4. Opciones de desarrollador
![e1b73b6e-06ec-42af-9790-71d78bd80863](https://user-images.githubusercontent.com/47721967/53671934-7c2dc200-3c4e-11e9-81cc-f751191e7f89.jpg)

5.Asi va el carrusel de fotos (ciertas partes ya traducidas)
![6d636c07-ef42-43ee-b69c-40994cb905ed](https://user-images.githubusercontent.com/47721967/53671956-949ddc80-3c4e-11e9-9949-304e5b76040d.jpg)
![b1f7b706-1116-4c24-bc8b-0dd1f2ec2acb](https://user-images.githubusercontent.com/47721967/53671962-9b2c5400-3c4e-11e9-8214-18a79598dc91.jpg)


Eso es todo lo que he visto , muchas gracias.

**Comment by danielchc** [comment]
Hola! He arreglado las 4 primeros puntos, el carrusel de fondos aún no porque es muy largo y en este momento no tengo tiempo. Espero que antes de que salga la nueva versión lo termine de traducir.

Gracias por todo, un saludo 😄

**Comment by danielchc** [comment]
Para la próxima versión de la ROM ya debería estar traducido el carrusel de fondos, he usado un traductor automático y revisado yo que estaba mal. Si encuentras algo que suene mal avísame 😄 

Saludos!!

**Comment by Davidjarod11** [comment]
Muchas Gracias por tu trabajo 😄  ... Sabes si esta semana habra rom? porque creo que dijeron que no habría, pero no sé si es en la global o en la china.

**Comment by danielchc** [comment]
La verdad es que no lo sé, no estoy seguro :-/
