### ISSUE TITLE
Traducción incorrecta de nombre de sonido.

### ISSUE THREAD

**Issue by hypersonik** [ingbrzy/MA-XML-10-SPANISH-Global#39]
- Aplicación: Ajustes.
- Frase incorrecta: "Primavera". La palabra original "Spring" se podría traducir por "Primavera", pero en este caso no es la traducción correcta, pues es el sonido de un muelle o resorte. Ambas palabras serían una buena traducción.
- Captura de pantalla:
![imagen](https://user-images.githubusercontent.com/29130376/53943891-6a20a900-40be-11e9-8b3c-045283182806.png)
- Dispositivo: Xiaomi Mi6
- Versión de ROM: MIUI 10 V10.2.1.0.OCACNFK (stable)

**Comment by danielchc** [comment]
Ya lo he cambiado, gracias por avisar!!
