### ISSUE TITLE
Nuevas traducciones 9.3.7 (Whyred)

### ISSUE THREAD

**Issue by Davidjarod11** [ingbrzy/MA-XML-10-SPANISH-Global#40]
1.
![whatsapp image 2019-03-08 at 00 58 50](https://user-images.githubusercontent.com/47721967/54010717-f2925e80-413d-11e9-8ac3-2230a818f209.jpeg)

2.
![whatsapp image 2019-03-08 at 00 58 50 2](https://user-images.githubusercontent.com/47721967/54010723-f7571280-413d-11e9-9a9e-84c2ac50f7fc.jpeg)

3.
![whatsapp image 2019-03-08 at 00 58 50 4](https://user-images.githubusercontent.com/47721967/54010730-ff16b700-413d-11e9-84b4-f4b40186c5fb.jpeg)
![whatsapp image 2019-03-08 at 00 58 50 3](https://user-images.githubusercontent.com/47721967/54010748-06d65b80-413e-11e9-8d5e-4f4684f4a3cd.jpeg)
![whatsapp image 2019-03-08 at 00 58 50 1](https://user-images.githubusercontent.com/47721967/54010755-0ccc3c80-413e-11e9-97f6-3434c44ccfff.jpeg)
![whatsapp image 2019-03-08 at 00 58 50 5](https://user-images.githubusercontent.com/47721967/54010736-0211a780-413e-11e9-89b4-8d38ab4e38c1.jpeg)

**Comment by danielchc** [comment]
Arreglado, muchas gracias como siempre
