### ISSUE TITLE
Nuevas traducciones 9.3.14 (Whyred)

### ISSUE THREAD

**Issue by Davidjarod11** [ingbrzy/MA-XML-10-SPANISH-Global#41]
1.
![d0248428-f77c-41b6-85ad-05f2ba9239fa (1)](https://user-images.githubusercontent.com/47721967/54529615-5ee73c00-494e-11e9-9595-42f0b460597c.jpg)
![5838402d-4d83-4403-bce3-5d96bcf00a14](https://user-images.githubusercontent.com/47721967/54530375-96ef7e80-4950-11e9-81d1-92163a15f985.jpg)

2.
![a14c8284-2be1-423d-9b18-e7ecb2812149](https://user-images.githubusercontent.com/47721967/54529625-673f7700-494e-11e9-8000-79a0b4b1fd5b.jpg)
EL cuadro de abajo aparece en ingles solo cuando esta activado el ahorrador de batería
![bd7d71b3-8af3-4a5e-9714-261cdca4e372](https://user-images.githubusercontent.com/47721967/54529634-6c9cc180-494e-11e9-9bf2-27f707f5b12f.jpg)
![cfcb3f4b-0ea0-4b5b-986f-4cca4c37352f](https://user-images.githubusercontent.com/47721967/54529760-d61cd000-494e-11e9-9279-3b39a423759e.jpg)
![cdf3a2e1-2535-42ea-b722-33eec1850ab2](https://user-images.githubusercontent.com/47721967/54623608-de9e0500-4a39-11e9-8945-7e9b4e1b36af.jpg)

 
3.
![4cc4d5cc-6f44-4d37-ab7a-c8d663f85755](https://user-images.githubusercontent.com/47721967/54530457-d322df00-4950-11e9-9fd7-85989cb09086.jpg)
![44e8aa52-1f9a-4ed7-b2b4-377ed0530050](https://user-images.githubusercontent.com/47721967/54530466-d9b15680-4950-11e9-8356-f838ea014d9e.jpg)

4. Dual apps 
![7b2ed4ea-1c32-4603-9bfe-7b541ec88df5](https://user-images.githubusercontent.com/47721967/54530807-c6eb5180-4951-11e9-9cd2-d554a1ae52ac.jpg)

**Comment by danielchc** [comment]
Hola! Le echo vistazo mañana, muchas gracias por avisar!

**Comment by danielchc** [comment]
Debería estar arreglado :-D

**Comment by Davidjarod11** [comment]
Muchas gracias :)
