### ISSUE TITLE
Traducción nueva ajustes galeria

### ISSUE THREAD

**Issue by pantxi11** [ingbrzy/MA-XML-10-SPANISH-Global#43]
Aplicación: Galería 
Sección: Ajustes de galería
Opción sin traducir: "Gallery's pics..."
Traducción:
Selecciones de la galería
Seleccionar mejor foto
MIUI analizará fotos que sean similares y marcará las mejores. Desactiva esta opción para borrar las marcas de las fotos.

![Screenshot_2019-03-22-18-48-12-641_com miui gallery](https://user-images.githubusercontent.com/48735062/54843556-eb8a5500-4cd4-11e9-817c-d77cae551988.png)

**Comment by danielchc** [comment]
Listo!
