### ISSUE TITLE
Traducciones 9.3.28 

### ISSUE THREAD

**Issue by Davidjarod11** [ingbrzy/MA-XML-10-SPANISH-Global#44]
Hola que tal, luego de actualizar a la ultima versión en mi redmi note 5 algunas opciones volvieron a estar en ingles, también lo reportan en el foro de xiaomi eu.

![WhatsApp Image 2019-03-29 at 11 16 14](https://user-images.githubusercontent.com/47721967/55247815-8d023100-5216-11e9-9cff-20d21da480ee.jpeg)

![WhatsApp Image 2019-03-29 at 11 16 35](https://user-images.githubusercontent.com/47721967/55248600-1bc37d80-5218-11e9-9280-85c638c9d6c0.jpeg)

![WhatsApp Image 2019-03-29 at 11 20 28](https://user-images.githubusercontent.com/47721967/55247852-a0150100-5216-11e9-8b0e-5c6c9464e9fd.jpeg)
![WhatsApp Image 2019-03-29 at 11 20 28 (1)](https://user-images.githubusercontent.com/47721967/55247858-a2775b00-5216-11e9-845c-51dfa520b218.jpeg)
![WhatsApp Image 2019-03-29 at 11 18 45](https://user-images.githubusercontent.com/47721967/55247912-bfac2980-5216-11e9-9380-9d507a77aec1.jpeg)
![WhatsApp Image 2019-03-29 at 11 19 03 (2)](https://user-images.githubusercontent.com/47721967/55247925-c63aa100-5216-11e9-9ba5-a9196e1090e8.jpeg)
Todos los permisos aparecen en inglés.
![WhatsApp Image 2019-03-29 at 11 17 13](https://user-images.githubusercontent.com/47721967/55247940-cc308200-5216-11e9-9f80-fc27c2cef0a1.jpeg)
![WhatsApp Image 2019-03-29 at 11 19 03 (1)](https://user-images.githubusercontent.com/47721967/55247943-cf2b7280-5216-11e9-81bc-0e0a03aaf9b7.jpeg)
![WhatsApp Image 2019-03-29 at 11 18 38](https://user-images.githubusercontent.com/47721967/55248086-1154b400-5217-11e9-871a-ad114bd87f33.jpeg)
![WhatsApp Image 2019-03-29 at 11 17 26](https://user-images.githubusercontent.com/47721967/55248102-19acef00-5217-11e9-90bb-61b00181856f.jpeg)
![WhatsApp Image 2019-03-29 at 11 19 03](https://user-images.githubusercontent.com/47721967/55248111-1ca7df80-5217-11e9-9f73-57b0166ea310.jpeg)
![WhatsApp Image 2019-03-29 at 11 30 22](https://user-images.githubusercontent.com/47721967/55248125-22052a00-5217-11e9-8b9d-b445c1185f7e.jpeg)
![f31d2c25-0a2e-45f3-87c8-0ff8903d527e](https://user-images.githubusercontent.com/47721967/55260505-9ac7ae80-5236-11e9-8e68-61375c589015.jpg)

![WhatsApp Image 2019-03-29 at 11 55 40](https://user-images.githubusercontent.com/47721967/55249335-d011d380-5219-11e9-9970-e08e6368afa2.jpeg)

Muchas gracias y disculpa todas las molestias, saludos.

**Comment by danielchc** [comment]
Estoy al tanto de eso, estoy mirando de solucionarlo gracias por avisar

**Comment by danielchc** [comment]
He solucionado parte en la commit b4463fd3f658c1d457c9391517f3a9a166b9f620, han actualizado el Redmi Note 5 a Android 9 por eso faltan tantas cosas por traducir

**Comment by danielchc** [comment]
Creo que he traducido la mayoría que faltaba, cualquier cosa ya sabes 😓 

Saludos

**Comment by Davidjarod11** [comment]
Grandioso , muchas gracias , eran bastantes cosas las que faltaban la verdad, y cuando sale una nueva versión de miui toda la traducción se realiza desde cero o como es el tema? pequeña duda xD

**Comment by danielchc** [comment]
No, es que al cambiar de sistema Android alguna de las cadenas que tenían un nombre en android 8, ahora tienen otro nombre en Android 9, entonces provoca que en realidad estén traducidas pero tienen otro id.

Espero que te pudiera solventar la duda 😄
