### ISSUE TITLE
No traducido

### ISSUE THREAD

**Issue by helloleyenda** [ingbrzy/MA-XML-10-SPANISH-Global#45]
1-Ajustes--notificaciones y barra de estado

2-collapse after touch
batter indicator
show icons for incoming notifications
app notifications

![1](https://user-images.githubusercontent.com/49959378/56686526-74c9e880-66d4-11e9-86d0-32c5dfe50101.png)

4-Redmi Note 7

5-MIUI 10.4  9.4.18 Weekly

**Comment by danielchc** [comment]
Arreglado en b36f8b16b85a12abad998077f508fd58c0f2dc74
