### ISSUE TITLE
Bug traducción settings.apk

### ISSUE THREAD

**Issue by gingernut1978** [ingbrzy/MA-XML-10-SPANISH-Global#46]
En Ajustes/Ajustes adicionales/Privacidad el apartado de localización cuando está Activado hay unos símbolos junto con el texto, esto viene de la línea 2416 en el Settings.apk que hay un (/ %1$s) después del texto Activado que causa está errata.

**Comment by danielchc** [comment]
Listo! Gracias por avisar!
