### ISSUE TITLE
Nuevas Traducciones 9.5.9 (Whyred)

### ISSUE THREAD

**Issue by Davidjarod11** [ingbrzy/MA-XML-10-SPANISH-Global#47]
Hola que tal , aquí traigo nuevas cosas para traducir.
![7f069261-efd7-4ddd-8cd6-7e5a9ae004f6](https://user-images.githubusercontent.com/47721967/57577858-2e9bb580-7446-11e9-954a-ec552dce6b3b.jpg)
![47ee2088-4c11-4e82-80af-d73a7d564d5e](https://user-images.githubusercontent.com/47721967/57577861-39eee100-7446-11e9-8a18-d9a7f3a302a9.jpg)
![cdec8535-1656-4a12-abff-23e76cab9212](https://user-images.githubusercontent.com/47721967/57577862-3d826800-7446-11e9-8589-5422e9598acc.jpg)
![f940a0fd-dde9-4e8e-938f-0fdb3ec6dd98](https://user-images.githubusercontent.com/47721967/57577864-4bd08400-7446-11e9-9743-984b1def634b.jpg)
![b3d578cc-b6d9-4e8d-ac6f-d8e6e9c390e8](https://user-images.githubusercontent.com/47721967/57577867-5d199080-7446-11e9-8c9d-3dd9434cb013.jpg)
![135d4ef1-070a-416c-8ef3-48e0aa5007be](https://user-images.githubusercontent.com/47721967/57577869-5ee35400-7446-11e9-9597-eb47ac947e02.jpg)
![834b8643-b3f2-4f68-b8e4-14f475c1cb73](https://user-images.githubusercontent.com/47721967/57577870-6145ae00-7446-11e9-9e55-2ff7b775281a.jpg)
![945b8655-1d51-4e12-9c0c-a462ef207794 (1)](https://user-images.githubusercontent.com/47721967/57578244-cbae1c80-744d-11e9-8dc7-37ce3e812397.jpg)

![dba677ab-5bfd-4d8e-9083-1bf3c9fddc2d (1)](https://user-images.githubusercontent.com/47721967/57577875-7faba980-7446-11e9-85bd-a4c9f71c2de6.jpg)
![90e6d9f0-8633-4d24-b037-0ddd460e176e](https://user-images.githubusercontent.com/47721967/57577876-820e0380-7446-11e9-9cd7-0bdd4c52b275.jpg)
![25e59942-da8c-4edb-af9e-f4c015b23936](https://user-images.githubusercontent.com/47721967/57577879-876b4e00-7446-11e9-9c51-3d512f3e1a71.jpg)
![7214123d-d960-48c3-92d0-9b137d534b01](https://user-images.githubusercontent.com/47721967/57577881-8a663e80-7446-11e9-8e7c-48a3cb4e99f8.jpg)
![81c78bd2-20c4-4ac9-ab26-f13d15c1f573](https://user-images.githubusercontent.com/47721967/57577882-8e925c00-7446-11e9-97a1-fb70aa941b25.jpg)
![4340e780-e224-405a-8c95-5621c91419d2](https://user-images.githubusercontent.com/47721967/57577983-a36fef00-7448-11e9-844e-f829b96d4db2.jpg)
![d6e69be0-d86b-425f-9c9b-b7f4f79f0b53](https://user-images.githubusercontent.com/47721967/57577984-a834a300-7448-11e9-8e1e-fc2dbab6c069.jpg)
![15ecdba6-a769-40a6-bd88-8c6e997acf32](https://user-images.githubusercontent.com/47721967/57578035-39584980-744a-11e9-85df-6da00abce569.jpg)
![b3105ff9-737c-41b6-81af-0e5b6055685b](https://user-images.githubusercontent.com/47721967/57578036-3bbaa380-744a-11e9-9ac5-b03d16d01f88.jpg)
![3b71cae3-ae10-4863-a04f-1b9fc53affe2](https://user-images.githubusercontent.com/47721967/57578068-0bbfd000-744b-11e9-9663-fbd6d4f817a0.jpg)
![968a0ad9-c4ec-4516-af2b-a0265d5f51ba](https://user-images.githubusercontent.com/47721967/57578069-0cf0fd00-744b-11e9-97c6-b1254750d81d.jpg)
![bd9cbbc1-edb1-4278-bcf2-3c2b7b7e2e3a](https://user-images.githubusercontent.com/47721967/57578070-0d899380-744b-11e9-8520-addbb4b0d2ec.jpg)
![dc151481-6d8d-4bff-a093-0a7f86a8d719](https://user-images.githubusercontent.com/47721967/57578071-0ebac080-744b-11e9-975c-cf6c3bd5cc70.jpg)
Algunas opciones de acceso especial de aplicaciones en privacidad salen sin traducir.
![87e1c0d0-eb36-4bae-ba94-a110a6c6abbf](https://user-images.githubusercontent.com/47721967/57578080-3b6ed800-744b-11e9-9e3e-29c5db7b50ea.jpg)

Game Turbo
![b9a8e2d8-ab7d-41a0-b0c9-3232ee883ac4](https://user-images.githubusercontent.com/47721967/57578152-702f5f00-744c-11e9-8782-16455b7d3adb.jpg)
![05c5b1d0-db11-4aa3-b332-9b253a02aaf1](https://user-images.githubusercontent.com/47721967/57578153-702f5f00-744c-11e9-980e-13fc2926be9a.jpg)
![ac2537c8-ebed-4d8b-b4e8-3c34e1b9ea8c](https://user-images.githubusercontent.com/47721967/57578154-70c7f580-744c-11e9-9ae4-1871ea7e8da0.jpg)
![298af07d-61c0-48c2-b9f4-b6d49c4fa5cd](https://user-images.githubusercontent.com/47721967/57578155-70c7f580-744c-11e9-9ae5-931c0fffbc0b.jpg)
![68fcc731-bf54-43bd-b4b2-f24865374464](https://user-images.githubusercontent.com/47721967/57578208-2b57f800-744d-11e9-911f-58933c1c18e8.jpg)

El carrusel de fotos quedo muy bien , solo hay este pequeño detalle cuando cargan las cosas, muchas gracias por todo 😄

**Comment by danielchc** [comment]
Gracias por avisar! Intentaré arreglarlo pronto que este mes apenas voy a tener tiempo 😓

**Comment by danielchc** [comment]
Debería estar la mayoría solucionado, si encuentras algo más avisa 😄
