### ISSUE TITLE
Pantalla de bloqueo

### ISSUE THREAD

**Issue by ghost** [ingbrzy/MA-XML-10-SPANISH-Global#5]
En la pantalla de bloqueo cuando llevas el menú hacia la izquierda salen palabras en ingles, como muestro en la foto adjunta

![photo_2018-08-15_00-14-55](https://user-images.githubusercontent.com/33995653/44121433-43b2f780-a020-11e8-8ff4-ffffa831f767.jpg)

**Comment by coryweed** [comment]
Si.en el mi5 también aparecen en inglés

**Comment by nosijf982** [comment]
@ingbrzy Why don't appear translated?

https://github.com/ingbrzy/MA-XML-10-SPANISH-Global/blob/a6c0ed7ee2836f3ad43d14e9b9244057632bf0df/Spanish/main/MiuiHome.apk/res/values-es/strings.xml#L144

**Comment by ghost** [comment]
Creo que está solucionado al menos el último, el calendario y los contactos. Lo demás no estoy seguro si para la semana lo veis igual avisad :-)
