### ISSUE TITLE
Traducciones faltantes y errores (whyred) stable 10.3.5.0

### ISSUE THREAD

**Issue by cegulo29** [ingbrzy/MA-XML-10-SPANISH-Global#53]
![Screenshot_2019-08-25-18-13-54-019_com android settings](https://user-images.githubusercontent.com/54513428/63656011-8647fd80-c765-11e9-81d3-cc1bb76ec6a3.png)
![Screenshot_2019-08-25-18-14-09-143_com android settings](https://user-images.githubusercontent.com/54513428/63656015-89db8480-c765-11e9-8f21-0af7164566d1.png)

**Comment by danielchc** [comment]
Solucionado, gracias por avisar
