### ISSUE TITLE
Ajustes / Mi Cloud / Grabadora de llamadas

### ISSUE THREAD

**Issue by ghost** [ingbrzy/MA-XML-10-SPANISH-Global#7]
Cuando le das a Ajustes / Mi Cloud, y luego te vas a la opción de Grabadora de llamadas, y le das a activar la grabación de llamadas, en el mensaje que te aparece para enviar el SMS, hay una palabra en castellano que se ha colado una letra "i" entre medias. No tengo captura de esto

**Comment by ghost** [comment]
Sin captura no puedo hacer mucho

**Comment by coryweed** [comment]
No consigo encontrar lo que dices
