### ISSUE TITLE
 Notificaciones / Barra de estado

### ISSUE THREAD

**Issue by ghost** [ingbrzy/MA-XML-10-SPANISH-Global#8]
En el menu de Ajustes, Notificaciones y luego barra de estado, aparece la opción para poder bajar la barra de estado en la pantalla bloqueada, pero dicha opción aparece en ingles, te adjunto captura, esta en las ultimas opciones
![photo_2018-08-15_00-14-58](https://user-images.githubusercontent.com/33995653/44121525-af956000-a020-11e8-801c-6d425e43c020.jpg)

**Comment by ghost** [comment]
"Show on secure lock screen"

**Comment by coryweed** [comment]
Mostrar en la pantalla de bloqueo.pueden añadirlo a la traduccion

**Comment by ghost** [comment]
Hola, disculpa por tardar en responder. Estaba de vacaciones y no tuve tiempo de solucionarlo.Para la semana que viene debería estar todas tus "Issues" resueltas. 

Gracias!

**Comment by ghost** [comment]
Solucionado!
