### ISSUE TITLE
Un par de errores de traducción

### ISSUE THREAD

**Issue by partebragas** [ingbrzy/MA-XML-10-SPANISH-Global#9]
![screenshot_2018-08-15-09-49-16-253_com android browser](https://user-images.githubusercontent.com/40788593/44225561-29972780-a18e-11e8-9ec9-459a19c0f4d9.png)
![screenshot_2018-08-15-13-57-45-604_com miui home](https://user-images.githubusercontent.com/40788593/44225563-29972780-a18e-11e8-8116-32967dc03b12.png)

Muchas Gracias

**Comment by partebragas** [comment]
![screenshot_2018-07-14-08-00-36-090_org telegram messenger](https://user-images.githubusercontent.com/40788593/44225912-fdc87180-a18e-11e8-9a3b-c6c70bce9ba8.png)

esta es del mes pasado  no se si lo arreglaron pero la comparto.

**Comment by ghost** [comment]
Hola, mañana le echo un vistazo! 
Los del segundo mensaje deberían estar solucionados ya que cambiamos la base de la traducción para la global pero aún así le echaré un vistazo!
Gracias!!

**Comment by ghost** [comment]
Solucionado!

**Comment by partebragas** [comment]
Muchas Gracias
